version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: quiz_db
    restart: always
    environment:
      POSTGRES_USER: quiz
      POSTGRES_PASSWORD: quiz_pass
      POSTGRES_DB: quiz_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
